import { Injectable } from '@angular/core';
import { Question } from '../models/question.model';

@Injectable({ providedIn: 'root' })
export class QuestionsService {
  private readonly _questions: Question[] = this._buildQuestions();

  private _buildQuestions(): Question[] {
    // Raw compact answer data: [title, answer, comment]
    const answerData: [string, string, string][] = [
      ['Uso de vírgulas em orações adjetivas','B','A oração entre vírgulas é explicativa; a sem vírgulas é restritiva.'],
      ['Concordância com "fazer" temporal','A','No sentido temporal, "fazer" é impessoal: "Faz dois anos".'],
      ['Uso da crase','B','"Àquela" reúne a preposição "a" e o pronome "aquela".'],
      ['Oração objetiva indireta','C','"Necessitar de" exige complemento indireto.'],
      ['Conjunção "conquanto"','C','Equivale a "embora": ideia de concessão.'],
      ['Grafia correta','B','Exceção, pretensioso e discrição.'],
      ['Oração adjetiva restritiva','B','A ausência de vírgulas restringe o conjunto de candidatos.'],
      ['Regência de assistir','C','No sentido de ver, exige "assistir ao filme".'],
      ['Relação semântica','C','"Embora" introduz uma relação concessiva.'],
      ['Colocação pronominal','D','A colocação pronominal da alternativa D está adequada.'],
      ['Objeto direto','C','"O gabarito preliminar" recebe diretamente a ação de divulgar.'],
      ['Conectivos','D','Não obstante = todavia; destarte = portanto; consoante = conforme.'],
      ['Microservices reading','C','O texto destaca deploy independente e escalabilidade individual.'],
      ['Third conditional','A','Forma correta: had found – would not have crashed.'],
      ['Objetivo de CI/CD','B','Automatiza build, testes e deploy.'],
      ['Non-restrictive clause','B','A oração entre vírgulas é não restritiva.'],
      ['Significado de mitigate','C','Mitigate significa reduzir ou amenizar riscos.'],
      ['Conector temporal','A','As soon as significa "assim que".'],
      ['Sigla REST','B','Representational State Transfer.'],
      ['Voz passiva','A','The code was reviewed by the senior developer.'],
      ['Atomicity','C','Uma transação é concluída ou falha integralmente.'],
      ['Phrasal verb','A','Come up with significa elaborar uma solução.'],
      ['Technical debt','B','É o custo futuro de retrabalho por atalhos técnicos.'],
      ['Deprecated','B','Ainda funciona, mas não é recomendado para novos usos.'],
      ['Negação de implicação','B','A negação de P → Q é P ∧ ¬Q.'],
      ['Conjuntos: Java exclusivo','C','8 − 3 = 5 pessoas.'],
      ['Sequência numérica','B','A razão é 3; o próximo termo é 162.'],
      ['Probabilidade binomial','A','3 × 0,05 × 0,95² resulta em aproximadamente 13,5%.'],
      ['Negação de universal','B','"Todo A é B" se nega por "Algum A não é B".'],
      ['Reserva de vagas','B','25% negros, 3% indígenas e 2% quilombolas.'],
      ['Arquitetura de LLMs','C','LLMs são baseados na arquitetura Transformer.'],
      ['Prompt engineering','C','É a elaboração de instruções eficazes para modelos de IA.'],
      ['Técnica de machine learning','D','"Aprendizado Determinístico Sequencial" não é técnica reconhecida.'],
      ['COP30','C','Belém do Pará.'],
      ['Alucinação em IA','C','Resposta coerente na forma, mas factualmente incorreta.'],
      ['Base legal da LGPD','C','Curiosidade científica do controlador não é base legal.'],
      ['Papel do DPO','C','Canal de comunicação entre controlador, titulares e ANPD.'],
      ['Neutralidade de rede','B','É garantida pelo Marco Civil da Internet.'],
      ['ISO 27001','C','Trata do Sistema de Gestão de Segurança da Informação.'],
      ['Dados pessoais sensíveis','B','Exigem consentimento específico ou outra hipótese legal.'],
      ['Herança em OO','C','Permite herdar e especializar características de outra classe.'],
      ['Comparação de Strings em Java','B','== compara referência; equals compara conteúdo.'],
      ['@Autowired','C','Realiza injeção de dependência pelo container Spring.'],
      ['SQL: HAVING','B','Filtra desenvolvedores com mais de três projetos.'],
      ['HTTP PATCH','D','É o método para atualização parcial.'],
      ['Microsserviços','B','Database per service favorece o desacoplamento.'],
      ['Function<T, R>','C','Recebe T e retorna R.'],
      ['git merge','C','Combina alterações entre branches.'],
      ['Beans no Spring','B','São componentes gerenciados pelo container IoC.'],
      ['filter, map e reduce','B','Pares ao quadrado: 4 + 16 + 36 = 56.'],
      ['Foreign key','C','Garante integridade referencial entre tabelas.'],
      ['Imagem e container','C','Imagem é template; container é a instância em execução.'],
      ['Singleton','D','Garante uma única instância e ponto global de acesso.'],
      ['Product Backlog','C','Lista priorizada de funcionalidades e melhorias.'],
      ['Classe final','B','Não pode ser estendida por outras classes.'],
      ['JPA e Hibernate','B','Hibernate implementa a especificação JPA.'],
      ['Single Responsibility','D','Uma classe deve ter apenas um motivo para mudar.'],
      ['201 Created','C','Indica recurso criado com sucesso.'],
      ['Polimorfismo','B','Permite tratar diferentes objetos por uma abstração comum.'],
      ['CI/CD','B','Continuous Integration / Continuous Delivery ou Deployment.'],
      ['Streams Java','B','Filtra e ordena: Beatriz, Carlos, Daniel e Eduardo.'],
      ['@Injectable','B','Declara serviço disponível para injeção no Angular.'],
      ['TDD','C','Red, Green, Refactor.'],
      ['Fluxo Git','D','git add → git commit → git push.'],
      ['JWT','B','Autenticação stateless em aplicações e APIs.'],
      ['Índice em banco','B','Estrutura que acelera consultas.'],
      ['@GetMapping','C','Mapeia requisições HTTP GET.'],
      ['MVC','C','Model concentra dados e lógica de negócio.'],
      ['Containers Docker','B','Compartilham o kernel do host e são leves.'],
      ['typeof em JavaScript','B','null, arrays e objetos retornam object; undefined retorna undefined.'],
    ];

    const extraAnswerData: [string, string, string][] = [
      ['Métricas de software','B','Pontos de função e story points ajudam a estimar esforço e complexidade.'],
      ['Arquitetura de serviços','C','SOA organiza capacidades como serviços reutilizáveis e interoperáveis.'],
      ['REST e HTTP semântica','A','REST usa recursos e métodos HTTP para comunicação uniforme.'],
      ['TLS e certificados','D','Certificados digitais autenticam o servidor e apoiam a troca segura de chaves.'],
      ['Microsserviços e autonomia','C','Cada serviço deve ser independente no ciclo de desenvolvimento e operação.'],
      ['API Gateway','B','Gateway centraliza roteamento, segurança e composição de múltiplos serviços.'],
      ['Webhooks','A','Webhooks disparam eventos em tempo real para sistemas interessados.'],
      ['RPC versus REST','D','RPC foca em chamadas de procedimento remotas, enquanto REST foca em recursos.'],
      ['Monólito modular','C','Monólito pode ser bem estruturado, mas tende a crescer em acoplamento.'],
      ['Observabilidade','B','Métricas, logs e traces permitem entender o comportamento de sistemas distribuídos.'],
      ['Modelagem conceitual','A','Entidade, relacionamento e cardinalidade definem a representação do domínio.'],
      ['MER e DER','B','MER descreve regras de negócio, DER representa estruturas em banco.'],
      ['Integridade referencial','D','Chaves estrangeiras garantem que a relação entre tabelas seja consistente.'],
      ['ACID','C','Atomicidade, Consistência, Isolamento e Durabilidade são as propriedades fundamentais.'],
      ['Normalização','A','Reduz redundância e melhora consistência dos dados armazenados.'],
      ['SQL joins','B','JOIN combina linhas relacionadas entre tabelas por colunas correspondentes.'],
      ['SGBD e metadados','C','Metadados descrevem estrutura, uso e regras de manutenção do banco.'],
      ['Data warehouse','D','Data Warehouse centraliza dados históricos para suporte à decisão.'],
      ['OLAP e cubos','A','OLAP permite análise multidimensional com operações como slice e dice.'],
      ['NoSQL document','B','Document stores persistem registros em documentos JSON-like.'],
      ['ETL e ELT','C','ETL transforma antes do carregamento; ELT carrega primeiro e transforma depois.'],
      ['Big Data','A','Big Data trata de volume, variedade e velocidade de dados.'],
      ['Dashboard','D','Painel de BI visualiza indicadores e métricas de negócio.'],
      ['Data mining','B','Data mining procura padrões e tendências em grandes bases de dados.'],
      ['DW vs Data Mart','C','Data Mart é subconjunto orientado a um departamento, menor e mais específico.'],
      ['Coleta e mapeamento','A','Mapear fontes é essencial para garantir qualidade e rastreabilidade dos dados.'],
      ['ETL e qualidade','B','Validação e padronização impedem inconsistências em processos ETL.'],
      ['Governança de dados','C','Governança define políticas, responsabilidades e controles para uso dos dados.'],
      ['COBIT 2019','D','COBIT organiza governança e gestão de TI com objetivos e domínios.'],
      ['ITIL v4','A','ITIL organiza serviços de TI em cadeias de valor e práticas.'],
      ['BPMN','B','BPMN padroniza a modelagem de processos de negócio.'],
      ['PMBOK áreas','C','PMBOK organiza o conhecimento em grupos de processos.'],
      ['Risco em projetos','D','Identificar riscos é o primeiro passo para resposta e mitigação.'],
      ['Scrum eventos','A','Sprint, daily, review e retrospective são eventos essenciais.'],
      ['Kanban','B','Kanban visualiza fluxo de trabalho e limita WIP.'],
      ['Lean','C','Lean busca eliminar desperdícios e aumentar valor para o cliente.'],
      ['Change management','A','Mudança organizacional exige comunicação, suporte e acompanhamento.'],
      ['Cobertura de teste','B','Testes unitários e de integração melhoram confiabilidade e regressão.'],
      ['Gestão de configuração','C','Git e versionamento ajudam a controlar mudanças de software.'],
      ['Requisitos funcionais','D','Requisitos funcionais descrevem comportamento esperado da solução.'],
      ['Requisitos não funcionais','A','Disponibilidade, segurança e desempenho são exemplos de requisitos não funcionais.'],
      ['Métricas de produtividade','B','Story points e pontos de função ajudam a mensurar esforço.'],
      ['App híbrido','C','Apps híbridos reusam código web em camadas nativas.'],
      ['Performance front-end','A','Lighthouse e Core Web Vitals medem qualidade e velocidade de renderização.'],
      ['Acessibilidade web','B','A11y garante uso acessível para pessoas com diferentes necessidades.'],
      ['PWA','D','Progressive Web App combina UX web com capacidades de app nativo.'],
      ['HTTPS e TLS','C','HTTPS transmite dados sobre TLS, protegendo integridade e confidencialidade.'],
      ['Blockchain','A','Blockchain registra transações em blocos encadeados e imutáveis.'],
      ['Composição de serviços','B','Orquestração e choreografia coordenam interações entre microsserviços.']
    ];

    // Prompt and options data (abbreviated for the 70 questions)
    const promptsAndOptions: { p: string; o: string[] }[] = [
      {p:'A Dataprev, que é uma das maiores empresas de tecnologia do Brasil, anunciou vagas. Sobre o uso das vírgulas no período, é correto afirmar que:',o:['A primeira isola oração restritiva','As vírgulas em "que é uma das maiores empresas..." isolam oração explicativa','A segunda isola oração causal','Todas são facultativas','"que se prepararam..." é explicativa']},
      {p:'Assinale a alternativa em que a concordância verbal está INCORRETA:',o:['Fazem dois anos que a Dataprev não realizava concurso','A maioria dos candidatos se inscreveu','Mais de um desenvolvedor foi aprovado','Cerca de duzentas pessoas compareceram','Havia muitas vagas']},
      {p:'Assinale a alternativa que apresenta uso correto do sinal indicativo de crase:',o:['Chegou à prova','Referente àquela vaga','Disponível à partir de hoje','À todas as etapas','Devida à todos']},
      {p:'Em "A empresa necessita de que os candidatos comprovem experiência", a oração subordinada substantiva é:',o:['Subjetiva','Objetiva direta','Objetiva indireta','Completiva nominal','Predicativa']},
      {p:'Em "O desenvolvedor implementou a funcionalidade, conquanto encontrasse dificuldades técnicas", a conjunção expressa:',o:['Causa','Consequência','Concessão','Finalidade','Proporcionalidade']},
      {p:'Assinale a alternativa em que todas as palavras estão grafadas corretamente:',o:['Exceção – pretencioso – discrição','Exceção – pretensioso – discrição','Excessão – pretensioso – descrição','Exceção – pretensioso – descrição','Excessão – pretencioso – discrição']},
      {p:'Em "Os candidatos que estudaram bastante foram aprovados", a oração "que estudaram bastante" é:',o:['Adjetiva explicativa','Adjetiva restritiva','Substantiva subjetiva','Coordenada explicativa','Adverbial causal']},
      {p:'Assinale a frase que apresenta erro de regência verbal:',o:['Aspirava ao cargo','Visa ao preenchimento','Assistiu o filme','Esqueceu-se do prazo','Prefiro Java a Python']},
      {p:'Em "Embora o edital fosse extenso, o candidato leu-o integralmente", a relação entre as orações é de:',o:['Causa e consequência','Condição e resultado','Concessão e conclusão','Tempo e finalidade','Comparação e proporção']},
      {p:'Aponte a alternativa cuja colocação pronominal está de acordo com a norma-padrão:',o:['Me inscrevi','Nunca enganaram-me','Quem convidou-me','Os candidatos se prepararam','Não inscreva-se']},
      {p:'Na frase "A FGV divulgou o gabarito preliminar no site oficial", qual termo é objeto direto?',o:['A FGV','divulgou','o gabarito preliminar','no site oficial','do concurso']},
      {p:'"Não obstante", "Destarte" e "consoante" podem ser substituídas, respectivamente, por:',o:['Contudo – Portanto – conforme','Porquanto – Outrossim – mediante','Conquanto – Dessarte – durante','Todavia – Por conseguinte – segundo','Entretanto – Ademais – apesar de']},
      {p:'Segundo o texto sobre microservices, qual vantagem há em relação a monólitos?',o:['Menos documentação','Menor custo sempre','Deploy independente e escala individual','Sem API gateway','Sem banco de dados']},
      {p:'Complete: "If the developer ___ the bug earlier, the system ___ crashed."',o:['had found – would not have','found – would not','had found – will not have','finds – will not have','would find – had not']},
      {p:'Qual é o principal objetivo de uma pipeline CI/CD?',o:['Substituir revisões','Automatizar build, testes e deploy','Eliminar versionamento','Desenhar interfaces','Gerir orçamento']},
      {p:'Em "The API endpoint, which was deprecated last month, ...", a cláusula é:',o:['Restrictive','Non-restrictive','Conditional','Adverbial de tempo','Noun clause']},
      {p:'No contexto de segurança, "mitigate" pode ser substituído por:',o:['Increase','Ignore','Reduce','Document','Accelerate']},
      {p:'Complete: "The new feature will be released ___ the testing phase is completed."',o:['as soon as','despite','unless','while','however']},
      {p:'O que significa a sigla REST em serviços web?',o:['Remote Execution Standard Transfer','Representational State Transfer','Reliable Event Streaming Technology','Rapid Endpoint Service Transport','Reusable Enterprise Software Toolkit']},
      {p:'Identifique a frase com voz passiva correta:',o:['The code was reviewed by the senior developer','The code reviewed by the senior developer was','By the senior developer the code was reviewed','The senior developer was reviewed the code','Was reviewed the code']},
      {p:'Em transações ACID, Atomicity significa que uma transação:',o:['Pode ser parcial','É mais rápida','Tem sucesso ou falha como unidade','Cria backup','Exige confirmação']},
      {p:'Complete: "The development team needs to ___ a solution."',o:['come up with','come down with','come across','come over','come apart']},
      {p:'Em desenvolvimento, technical debt refere-se a:',o:['Custo de licenças','Retrabalho por atalho técnico','Salário da equipe','Depreciação de hardware','Juros de infraestrutura']},
      {p:'Em TI, deprecated significa:',o:['Recomendado','Suportado, mas não recomendado','Removido completamente','Aprovado pela gestão','Exigido por lei']},
      {p:'A negação de "Se o candidato estuda e pratica, então é aprovado" é:',o:['Não estuda ou não pratica e não é aprovado','Estuda e pratica, e não é aprovado','Se não estuda, não é aprovado','Não estuda e não pratica, ou é aprovado','É aprovado sse estuda e pratica']},
      {p:'8 pessoas usam Java, 6 Python e 3 ambas. Quantas usam exclusivamente Java?',o:['8','11','5','3','14']},
      {p:'Na sequência 2, 6, 18, 54, X, 486, qual é X?',o:['108','162','216','72','324']},
      {p:'Em 3 commits independentes, cada qual com 0,05 de chance de bug, a chance de exatamente um bug é:',o:['13,5%','5,0%','0,7%','15,0%','4,75%']},
      {p:'A negação de "Todos os sistemas críticos possuem backup automático" é:',o:['Nenhum possui','Algum crítico não possui','Todos não críticos possuem','Algum não crítico possui','Todos backups são críticos']},
      {p:'Sobre a Lei 15.142/2025, a distribuição correta da reserva de vagas é:',o:['Só Executivo','25% negros, 3% indígenas, 2% quilombolas','Não vale para Dataprev','20% negros e 10% indígenas','Não vale para concursos em andamento']},
      {p:'LLMs baseiam-se primariamente em qual arquitetura de rede neural?',o:['CNN','GAN','Transformer','Hopfield','Perceptron simples']},
      {p:'Sobre IA generativa, assinale a alternativa correta:',o:['Não produz código','Só cria texto','Prompt engineering cria instruções eficazes','Substitui desenvolvedores','Sempre repete o mesmo resultado']},
      {p:'Qual NÃO é uma técnica reconhecida de Machine Learning?',o:['Supervisionado','Não supervisionado','Por reforço','Determinístico Sequencial','Semi-supervisionado']},
      {p:'A COP30 foi realizada na cidade de:',o:['Rio de Janeiro','São Paulo','Belém do Pará','Manaus','Brasília']},
      {p:'Em IA, alucinação refere-se a:',o:['Gerar imagens','Consumo de energia','Informação coerente, mas incorreta','Indisponibilidade da API','Overfitting']},
      {p:'Qual NÃO constitui base legal para tratamento de dados na LGPD?',o:['Consentimento','Obrigação legal','Curiosidade científica do controlador','Execução de contrato','Legítimo interesse']},
      {p:'O encarregado/DPO, segundo a LGPD, deve:',o:['Aprovar orçamento','Desenvolver IA','Comunicar controlador, titulares e ANPD','Substituir controlador','Autorizar demissões']},
      {p:'Sobre o Marco Civil da Internet, é correto afirmar que:',o:['Provedor é sempre responsável','Garante neutralidade de rede','Permite comercialização livre de dados','Exige documento para acesso','Revogou o CDC']},
      {p:'A ISO 27001 estabelece requisitos para:',o:['Desenvolvimento ágil','Gestão de projetos','SGSI','Testes de usabilidade','Métricas de hardware']},
      {p:'Sobre o tratamento de dados pessoais sensíveis na LGPD:',o:['É sempre proibido','Pode ocorrer com consentimento específico ou hipótese legal','Não requer proteção especial','Só órgãos públicos podem tratar','É sempre autorizado para pesquisa']},
      {p:'No contexto de Orientação a Objetos, qual princípio permite que uma classe herde características de outra?',o:['Encapsulamento','Polimorfismo','Herança','Abstração','Composição']},
      {p:'Considere: String a = "Dataprev"; String b = "Dataprev"; String c = new String("Dataprev"); Qual é a saída de a == b, a == c e a.equals(c)?',o:['false, false, false','true, false, true','true, true, true','false, true, false','true, false, false']},
      {p:'Sobre o Spring Framework, a anotação @Autowired é utilizada para:',o:['Criar tabelas automaticamente','Configurar ORM','Realizar injeção de dependência automática pelo container Spring','Definir endpoints REST','Definir escopo prototype']},
      {p:'A consulta SQL com GROUP BY d.nome, HAVING COUNT(*) > 3 retorna:',o:['Todos os desenvolvedores, sem filtros','Apenas desenvolvedores com mais de 3 projetos, em ordem decrescente','O total geral de projetos','Desenvolvedores com exatamente 3 projetos','A lista completa de projetos']},
      {p:'Em APIs RESTful, qual método HTTP atualiza parcialmente um recurso existente?',o:['PUT','POST','DELETE','PATCH','GET']},
      {p:'Sobre a arquitetura de microsserviços, assinale a alternativa correta:',o:['Todos devem compartilhar o mesmo banco','Cada serviço deve ter seu próprio banco','São incompatíveis com Docker','A comunicação deve ser só síncrona','Eliminam testes de integração']},
      {p:'A interface java.util.function.Function<T, R> representa:',o:['Consumidor sem retorno','Fornecedor sem entrada','Função que aceita T e retorna R','Predicado booleano','Operação binária']},
      {p:'Qual comando Git combina alterações de uma branch secundária na branch principal?',o:['git commit','git push','git merge','git clone','git fetch']},
      {p:'O que são Beans no contexto do Spring Framework?',o:['Entidades exclusivas de banco','Componentes gerenciados pelo container IoC','Arquivos XML obrigatórios','Endpoints REST automáticos','Anotações de documentação']},
      {p:'Qual é a saída de filter pares, map quadrado e reduce soma sobre [1, 2, 3, 4, 5, 6]?',o:['20','56','36','44','0']},
      {p:'Em SQL, qual é a função de uma Foreign Key?',o:['Acelerar consultas','Criptografar dados','Garantir integridade referencial entre tabelas','Criar índices automaticamente','Definir o tipo de dado']},
      {p:'Em Docker, qual é a diferença entre uma imagem e um container?',o:['Ambos são a mesma coisa','Container é template; imagem é instância','Imagem é template; container é a instância em execução','Imagens são usadas apenas em produção','Containers não podem ser reiniciados']},
      {p:'Qual padrão de projeto garante que uma classe tenha apenas uma instância com ponto global de acesso?',o:['Factory','Observer','Strategy','Singleton','Decorator']},
      {p:'No Scrum, o Product Backlog é:',o:['O cronograma do projeto','A lista de bugs encontrados','Lista priorizada de funcionalidades e melhorias','O diário do time','O contrato com o cliente']},
      {p:'Em Java, uma classe declarada como "final" não pode ser:',o:['Instanciada','Estendida por outras classes','Compilada','Importada','Usada como tipo']},
      {p:'Sobre JPA e Hibernate, é correto afirmar que:',o:['São a mesma coisa','Hibernate implementa a especificação JPA','JPA é exclusivo do Spring','Hibernate substitui o banco de dados','JPA não suporta relacionamentos']},
      {p:'O princípio Single Responsibility do SOLID estabelece que:',o:['Interfaces devem ser coesas','Código não deve mudar','Dependências devem ser abstraídas','Uma classe deve ter apenas um motivo para mudar','Módulos devem ser abertos para herança']},
      {p:'Em HTTP, o código de status 201 indica:',o:['Sucesso na leitura','Redirecionamento','Recurso criado com sucesso','Erro de autenticação','Erro interno do servidor']},
      {p:'Polimorfismo em OO permite:',o:['Ocultar atributos','Tratar diferentes objetos por uma abstração comum','Criar múltiplas instâncias','Eliminar herança','Compartilhar estado global']},
      {p:'CI/CD significa:',o:['Code Integration / Code Deployment','Continuous Improvement / Continuous Documentation','Continuous Integration / Continuous Delivery ou Deployment','Common Interface / Common Design','Client Integration / Client Deployment']},
      {p:'Usando streams Java: filtrar maiores de 18, ordenar por nome e retornar lista: qual resultado para [Ana-25, Beatriz-20, Carlos-22, Daniel-30, Eduardo-17]?',o:['Ana, Beatriz, Carlos, Daniel','Beatriz, Carlos, Daniel e Eduardo','Ana, Carlos e Daniel','Beatriz, Eduardo, Carlos','Beatriz, Carlos, Daniel']},
      {p:'No Angular, @Injectable com providedIn: "root" significa:',o:['O serviço só funciona em módulos','Declara serviço disponível para injeção no Angular','O serviço é privado','Exige importação manual','Desabilita injeção de dependência']},
      {p:'TDD (Test-Driven Development) segue o ciclo:',o:['Plan, Code, Test','Write, Deploy, Monitor','Red, Green, Refactor','Code, Test, Deploy','Design, Build, Verify']},
      {p:'No fluxo básico do Git, qual é a sequência correta para enviar alterações?',o:['git commit → git add → git push','git push → git add → git commit','git fetch → git add → git push','git add → git commit → git push','git init → git add → git commit']},
      {p:'JWT (JSON Web Token) é utilizado principalmente para:',o:['Armazenar dados no banco','Autenticação stateless em aplicações e APIs','Compressão de arquivos','Criptografia simétrica','Gerenciamento de sessões com cookie']},
      {p:'Em banco de dados, o propósito de um índice é:',o:['Garantir unicidade','Estrutura que acelera consultas','Criar backup automático','Definir relacionamentos','Controlar transações']},
      {p:'No Spring MVC, @GetMapping é utilizado para:',o:['Mapear requisições HTTP POST','Mapear requisições de autenticação','Mapear requisições HTTP GET','Definir model de banco','Configurar injeção']},
      {p:'No padrão MVC, o Model é responsável por:',o:['Renderizar a interface','Tratar requisições HTTP','Model concentra dados e lógica de negócio','Definir rotas','Controlar sessões']},
      {p:'Docker containers, comparados a VMs, são caracterizados por:',o:['Precisar de hypervisor','Compartilham o kernel do host e são leves','Maior tempo de inicialização','Isolamento total do kernel','Não suportam redes']},
      {p:'Em JavaScript, o operador typeof retorna "object" para:',o:['undefined','null, arrays e objetos retornam object; undefined retorna undefined','string','number','boolean']},
    ];

    const extraPromptsAndOptions: { p: string; o: string[] }[] = [
      { p: 'Qual métrica é comumente usada para estimar esforço funcional em software?', o: ['Story Points', 'Pontos de função', 'Latency', 'Backlog Plan', 'Version tag'] },
      { p: 'Em SOA, o princípio principal é:', o: ['Concatenar processos em uma camada única', 'Expor capacidades como serviços reutilizáveis', 'Forçar acoplamento direto entre funções', 'Substituir toda interface por banco de dados', 'Usar somente arquivos XML embutidos'] },
      { p: 'No estilo arquitetural REST, a unidade de comunicação principal é:', o: ['Sessão persistente', 'Recurso identificado por URI', 'Socket de rede fixo', 'Arquivo de configuração', 'Módulo de cache'] },
      { p: 'Qual mecanismo autentica um servidor em HTTPS?', o: ['Token JWT do cliente', 'Certificado digital', 'Cookie de sessão', 'Chave pública embutida', 'Arquivo .env'] },
      { p: 'Em microsserviços, o que é mais desejável para autonomia?', o: ['Banco compartilhado entre todos os serviços', 'Deployment e manutenção independentes', 'Comunicação síncrona obrigatória', 'Uma única interface de UI', 'Dependência em um único pipeline'] },
      { p: 'O papel de um API Gateway é:', o: ['Substituir o banco de dados', 'Centralizar autenticação, roteamento e composição', 'Executar código no cliente', 'Reduzir o número de endpoints externos', 'Controlar somente logs de infraestrutura'] },
      { p: 'Um webhook é indicado para:', o: ['Transferência de arquivos em lote', 'Notificações em tempo real', 'Armazenar backup', 'Diminuir latência de rede', 'Substituir testes automatizados'] },
      { p: 'Qual diferença principal entre RPC e REST?', o: ['RPC é orientado a recursos e REST a rotinas', 'RPC centra chamada remota de procedimento; REST centra recursos', 'REST não usa HTTP', 'RPC elimina JSON', 'REST é sempre síncrono'] },
      { p: 'Qual característica é típica de um monólito bem estruturado?', o: ['Nenhuma separação de responsabilidades', 'Módulos com acoplamento mínimo', 'Uma camada única para toda a regra', 'Sem deploy em produção', 'Banco de dados compartilhado sem modelo'] },
      { p: 'Qual conjunto ajuda a responder “o que está acontecendo no sistema?”', o: ['Observabilidade', 'Polimorfismo', 'Caching local', 'ETL reverso', 'Versionamento manual'] },
      { p: 'Na modelagem conceitual, o principal foco é:', o: ['Representar regras do negócio e relacionamentos do domínio', 'Descrever a API REST', 'Versionar o código-fonte', 'Configurar o sitemap', 'Criar views gráficas'] },
      { p: 'MER e DER se diferenciam porque:', o: ['MER é conceitual e DER é físico/implementação', 'MER é a versão em SQL', 'DER não representa relacionamentos', 'MER é usado somente em BI', 'DER não usa entidades'] },
      { p: 'A função de uma chave estrangeira é:', o: ['Acelerar acesso em cache', 'Garantir integridade referencial', 'Substituir índices', 'Criar backup', 'Definir coluna auto increment'] },
      { p: 'ACID em transações de banco de dados significa:', o: ['Atomicidade, Consistência, Isolamento e Durabilidade', 'Agilidade, Confiabilidade, Integridade e Disponibilidade', 'Autorização, Criptografia, Integração e Deploy', 'Acesso, Consumo, Indexação e Distribuição', 'Análise, Controle, Integração e Diagnóstico'] },
      { p: 'Qual é o objetivo da normalização?', o: ['Aumentar redundância', 'Reduzir inconsistências e redundância', 'Substituir índices', 'Transformar dados em JSON', 'Definir interface Gráfica'] },
      { p: 'Em SQL, o JOIN é usado para:', o: ['Juntar colunas em arrays', 'Combinar linhas relacionadas entre tabelas', 'Reordenar a base em ordem alfabética', 'Fechar transações', 'Salvar backup'] },
      { p: 'O que um SGBD armazena em metadados?', o: ['Somente registros de negócio', 'Estrutura, regras e definições da base', 'Métrica de latência final', 'Somente índices semânticos', 'Tokens de autenticação'] },
      { p: 'A finalidade de um Data Warehouse é:', o: ['Armazenar exatamente uma tabela de logs', 'Centralizar dados históricos para apoio à decisão', 'Aplicar somente cache de API', 'Substituir o ETL', 'Executar algoritmos em memória'] },
      { p: 'OLAP permite análise:', o: ['Somente em arquivos texto', 'Multidimensional com operações de cubo', 'Somente em banco relacional sem índices', 'Somente em modelagem relacional', 'Sem uso de dados históricos'] },
      { p: 'Em NoSQL, um document store costuma persistir dados em:', o: ['Planilhas binárias', 'Documentos estruturados tipo JSON', 'Arquivos de imagem', 'Tabelas em CSV', 'Objetos de memória sem serialização'] },
      { p: 'Em ETL, o passo de transformação ocorre:', o: ['Antes do carregamento', 'Depois do carregamento', 'Somente no cliente', 'Somente em memória', 'Nunca em fluxo de dados'] },
      { p: 'Big Data é associado a:', o: ['Volume, variedade e velocidade', 'Somente CAPEX baixo', 'Apenas banco relacional', 'Apenas integrações SOAP', 'Somente dados estáticos'] },
      { p: 'Qual é a principal finalidade de um dashboard?', o: ['Registrar backup do banco', 'Visualizar métricas e indicadores', 'Substituir o front-end', 'Gerenciar código-fonte', 'Definir SLA de rede'] },
      { p: 'Data Mining tem foco em:', o: ['Gerar dumps satélites', 'Descobrir padrões em grandes volumes de dados', 'Substituir a modelagem dimensional', 'Apenas documentação de requisitos', 'Reduzir o número de usuários'] },
      { p: 'O que é um Data Mart?', o: ['Um banco de dados cliente-único', 'Um subconjunto de dados orientado a um departamento', 'Uma API sem documentação', 'Uma base somente para logs', 'Um repositório de imagens'] },
      { p: 'Na etapa de coleta de dados para BI, o principal cuidado é:', o: ['Ignorar origem do dado', 'Mapear fontes e validar rastreabilidade', 'Usar um único arquivo CSV', 'Manter somente metadados', 'Substituir fluxo por planilhas'] },
      { p: 'Qual é o papel da validação em ETL?', o: ['Aumentar custo operacional sem ganho', 'Garantir consistência e qualidade antes de uso', 'Substituir regras de negócio', 'Diminuir o número de tabelas', 'Evitar qualquer documentação'] },
      { p: 'Governança de dados se preocupa com:', o: ['Somente acesso físico ao datacenter', 'Políticas, responsabilidades e controles de uso', 'Apenas desenho de telas', 'Apenas revisão de código', 'Homologação de front-end'] },
      { p: 'O COBIT 2019 é um framework voltado a:', o: ['Criptografia de dados sem política', 'Governança e gestão de TI', 'Desenvolvimento de apps web', 'Modelagem de entidades', 'Pipeline de testes automatizados'] },
      { p: 'O ITIL v4 organiza serviços de TI em:', o: ['Funções estatísticas', 'Cadeia de valor e práticas', 'Modelos de machine learning', 'Regras de UX', 'Blocos de infraestrutura'] },
      { p: 'BPMN tem como principal objetivo:', o: ['Gerir métricas de performance', 'Modelar processos de negócio', 'Fazer deploy de containers', 'Criar esquemas de banco', 'Definir arquitetura de API'] },
      { p: 'PMBOK organiza o conhecimento em:', o: ['Áreas e grupos de processos', 'Módulos de front-end', 'Pedidos de implementação', 'Linguagens de banco', 'Padrões de teste'] },
      { p: 'Qual é o primeiro passo no tratamento de riscos?', o: ['Eliminá-los por completo', 'Identificá-los e avaliá-los', 'Apenas registrá-los em planilha', 'Criar backup imediato', 'Fazer sprint sem planejamento'] },
      { p: 'Quais eventos são centrais no Scrum?', o: ['Sprint, Daily, Review e Retrospective', 'Deploy e rollback', 'Taskboard e release', 'RTO e RPO', 'Sprint, KPI e backlog'] },
      { p: 'Kanban é conhecido por:', o: ['Impulsionar execução sem limitação de WIP', 'Visualizar fluxo e limitar itens em andamento', 'Apenas gerenciar código em repositórios', 'Eliminar reuniões de planejamento', 'Substituir toda documentação'] },
      { p: 'Lean busca principalmente:', o: ['Eliminar desperdícios e aumentar valor', 'Multiplicar tarefas redundantes', 'Aumentar o número de etapas', 'Acrescentar complexidade sem benefício', 'Ignorar feedback do cliente'] },
      { p: 'Qual atividade é essencial para gestão de mudança organizacional?', o: ['Comunicar, treinar e acompanhar', 'Eliminar toda documentação', 'Desativar o backlog', 'Usar somente ferramenta manual', 'Substituir dados por plano de ação'] },
      { p: 'Qual combinação melhora a confiabilidade de software?', o: ['Teste manual exclusivo', 'Tests unitários e de integração', 'Só revisão de código', 'Sem deploy em ambiente de homologação', 'Sem automação de build'] },
      { p: 'Git e versionamento ajudam principalmente a:', o: ['Controlar mudanças e histórico de trabalho', 'Bloquear toda execução de teste', 'Criar o banco de dados', 'Substituir o DPO', 'Controle de acesso físico'] },
      { p: 'Requisitos funcionais descrevem:', o: ['Comportamento esperado da solução', 'Apenas normas de hardware', 'Somente visão estética', 'Métricas de produção', 'Serviços de suporte'] },
      { p: 'Requisitos não funcionais incluem, por exemplo:', o: ['Disponibilidade, segurança e desempenho', 'Somente lista de tarefas', 'Apenas comentários de código', 'Nome de equipe', 'Objetivos financeiros sem relação técnica'] },
      { p: 'Qual instrumentação ajuda a medir produtividade e esforço em desenvolvimento?', o: ['Story points', 'Time to market', 'Queue de impressão', 'Branch names', 'Hex color palette'] },
      { p: 'Um app híbrido é caracterizado por:', o: ['Código web empacotado em camada nativa', 'Somente desenvolvimento nativo', 'Sem interface', 'Uso exclusivo de shell script', 'Não depender de adaptadores'] },
      { p: 'Qual ferramenta de performance mede qualidade de renderização e UX web?', o: ['Lighthouse', 'Git checkout', 'Jenkins sem build', 'BPMN file', 'SQL dump'] },
      { p: 'Acessibilidade web tem como foco principal:', o: ['Suprimir feedback de usuário', 'Permitir uso inclusivo e compreensível', 'Remover todos os textos', 'Apenas diminuir a largura da tela', 'Ignorar teclado'] },
      { p: 'PWA é conhecida por:', o: ['Sumir em modo offline', 'Combinar UX web com capacidades de app nativo', 'Ser exclusiva para desktop', 'Não suportar notificações', 'Usar somente HTTP'] },
      { p: 'HTTPS protege comunicação usando:', o: ['Somente HTTP sem criptografia', 'TLS sobre HTTP', 'FTP e pipeline', 'JSON puro sem chave', 'Token em querystring'] },
      { p: 'Blockchain é reconhecida por:', o: ['Registro imutável em blocos encadeados', 'Permitir alteração irrestrita em cada bloco', 'Substituir completamente o banco relacional', 'Ser útil apenas em tabelas planas', 'Não ter integração com APIs'] },
      { p: 'Em arquiteturas distribuídas, orquestração e choreografia ajudam a:', o: ['Dar autonomia e coordenação entre serviços', 'Substituir regras de negócio', 'Eliminar toda comunicação via API', 'Remover logs e métricas', 'Fechar filas do banco'] }
    ];

    const allAnswerData = [...answerData, ...extraAnswerData];
    const allPromptsAndOptions = [...promptsAndOptions, ...extraPromptsAndOptions];

    return allAnswerData.map(([title, answer, comment], index) => ({
      number: index + 1,
      title,
      answer,
      comment,
      prompt: allPromptsAndOptions[index]?.p || '',
      options: allPromptsAndOptions[index]?.o || [],
      concept: comment
    }));
  }

  getAll(): Question[] { return this._questions; }
  getByNumber(num: number): Question | undefined { return this._questions.find(q => q.number === num); }
  getBySubjectRange(from: number, to: number): Question[] {
    return this._questions.filter(q => q.number >= from && q.number <= to);
  }
  search(query: string, subjectId?: string, from?: number, to?: number): Question[] {
    let list = this._questions;
    if (from !== undefined && to !== undefined) {
      list = list.filter(q => q.number >= from && q.number <= to);
    }
    if (!query) return list;
    const q = query.toLowerCase();
    return list.filter(qt => qt.title.toLowerCase().includes(q) || qt.prompt.toLowerCase().includes(q));
  }
}
