name: Deploy Frontend (GitHub Pages)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  frontend-deploy:
    name: Build & Deploy Frontend (Angular)
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: 'angular-app/package-lock.json'

      - name: Install dependencies & Build Angular
        working-directory: ./angular-app
        run: |
          npm ci
          npx ng build --configuration production --base-href /concurso-dev/
          cp dist/angular-app/browser/index.html dist/angular-app/browser/404.html

      - name: Upload artifact for GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'angular-app/dist/angular-app/browser'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4